# Generated by Django 4.2.13 on 2024-06-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estac',
            fields=[
                ('nombre', models.CharField(blank=True, db_column='Nombre', null=True)),
                ('id_estacion', models.BigIntegerField(db_column='Id_Estacion', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Estac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicionescombinadas',
            fields=[
                ('velvient', models.FloatField(blank=True, null=True)),
                ('direcvien', models.IntegerField(blank=True, null=True)),
                ('id_estacion', models.BigIntegerField(blank=True, null=True)),
                ('pluvi', models.FloatField(blank=True, null=True)),
                ('fecha_med_lec', models.DateTimeField(blank=True, null=True)),
                ('presionat', models.FloatField(blank=True, null=True)),
                ('fecha_lec_sen', models.DateTimeField(blank=True, null=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('humedad', models.FloatField(blank=True, null=True)),
                ('id_sensor', models.BigIntegerField(blank=True, null=True)),
                ('id_med', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'medicionescombinadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mediclima',
            fields=[
                ('id_med', models.BigIntegerField(db_column='Id_Med', primary_key=True, serialize=False)),
                ('velvient', models.FloatField(blank=True, db_column='VelVient', null=True)),
                ('direcvien', models.IntegerField(blank=True, db_column='DirecVien', null=True)),
                ('pluvi', models.FloatField(blank=True, db_column='Pluvi', null=True)),
                ('fecha_med_lec', models.DateTimeField(db_column='Fecha_Med_Lec')),
            ],
            options={
                'db_table': 'MediClima',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensorgen',
            fields=[
                ('presionat', models.FloatField(blank=True, db_column='PresionAt', null=True)),
                ('id_estacion', models.OneToOneField(db_column='Id_Estacion', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='estaciones.estac')),
                ('fecha_lec_sen', models.DateTimeField(db_column='Fecha_Lec_Sen')),
                ('temperatura', models.FloatField(blank=True, db_column='Temperatura', null=True)),
                ('humedad', models.FloatField(blank=True, db_column='Humedad', null=True)),
                ('id_sensor', models.BigIntegerField(db_column='Id_Sensor')),
            ],
            options={
                'db_table': 'SensorGen',
                'managed': False,
            },
        ),
    ]
