# Generated by Django 5.0.6 on 2024-07-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newlectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lectura', models.IntegerField(blank=True, null=True)),
                ('id_estacion', models.CharField(blank=True, max_length=50, null=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('humedad', models.FloatField(blank=True, null=True)),
                ('presionatmosferica', models.FloatField(blank=True, null=True)),
                ('velocidad_del_viento', models.FloatField(blank=True, null=True)),
                ('direccion_del_viento', models.FloatField(blank=True, null=True)),
                ('pluvialidad', models.FloatField(blank=True, null=True)),
                ('hora', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'newlectura',
            },
        ),
    ]
