# Generated by Django 5.0.6 on 2024-07-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0003_sensor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicionescombinadas',
        ),
        migrations.DeleteModel(
            name='Sensorgen',
        ),
    ]
