# Generated by Django 4.2.13 on 2024-07-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0004_delete_medicionescombinadas_delete_sensorgen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mediclima',
        ),
        migrations.RemoveField(
            model_name='newlectura',
            name='id_estacion',
        ),
        migrations.AddField(
            model_name='newlectura',
            name='estacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='estaciones.estac'),
        ),
    ]
