# Generated by Django 4.2.13 on 2024-07-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0005_delete_mediclima_remove_newlectura_id_estacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlectura',
            name='sensores',
            field=models.ManyToManyField(blank=True, related_name='lecturas', to='estaciones.sensor'),
        ),
    ]
