# Generated by Django 4.2.13 on 2024-07-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0006_newlectura_sensores'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estac',
            table='estac',
        ),
    ]
