# Generated by Django 4.2.13 on 2024-07-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0008_rename_estacion_newlectura_id_estacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newlectura',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='sensor',
            table='sensor',
        ),
    ]
